<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>系统错误</title>
<style type="text/css">
*{ margin:0px; padding:0px;}
body { background-color:#f3f3f3; text-align:center;}
.main{
	width:700px;
	min-height:300px;
	margin-top: 100px;
	margin-right: auto;
	margin-bottom: 100px;
	margin-left: auto;
}
.qingwa{ float:left; width:300px; display:block;}
.right{ float:right; width:400px; text-align:center;}
.clear{ clear:both; height:1px; line-height:1px; font-size:1px;}
.silingsi{
	font-size:200px;
	font-family:Arial;
	color: #666;
	line-height: 200px;
}
.jieshi{
	font-family:"微软雅黑";
	font-size:18px;
	line-height: 30px;
	color: #666;
}
.fan{ padding-top:10px;}
.fan a{ display:inline-block;border-radius:4px;background-color:#fff; border:solid 1px #d5d5d5; text-decoration:none; font-family:"微软雅黑"; line-height:32px; height:32px; font-size:14px; color:#666; padding-left:25px; padding-right:25px;}
.fan a:hover{border:solid 1px #999;}
</style>
</head>

<body>
<div class="main">
<div class="qingwa"><img src="<?php echo $this->basePath('public'); ?>/images/qingwa.png" width="260" height="260" /></div>
<div class="right">
	<div class="silingsi"><?php echo $code; ?></div>
    <div class="jieshi"><?php echo $msg; ?></div>
    <div class="fan"><a href="<?php echo $this->url(''); ?>">返回首页</a></div>
</div>
<div class="clear"></div>
</div>
</body>
</html>

