<!DOCTYPE HTML>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo  isset($seo_title)?$seo_title:"美业连锁管理平台" ?></title>
<?php $this->import('/_include/global')?>
</head>
<body>
<?php $this->import('/_include/header');?>
<!--内容-->
<div class="page_content_wrapper">
	<div class="page_content" style="min-height:1006px; margin-left:180px;">
    	<?php echo $content; ?>
    </div>
</div>
<?php $this->import('/_include/footer')?>
</body>
</html>