<div class="page_add">
	<span class="plat_shai" id='add_act'>添加</span>
	<span class="page_add_span" style="width:0px"></span>
	<span class="page_add_text">商品管理 &gt; 商品分类</span>
</div>
<div style="text-align:left;" class="page">

<?php foreach ($topCate as $key => $value): ?>
	<fieldset>
		<legend><?php echo $value ?></legend>
		<?php if ($childCate[$key]): ?>
			<ul>
			<?php foreach ($childCate[$key] as $child): ?>
				<li><?php echo $child['name'] ?></li>
			<?php endforeach ?>
			</ul>
		<?php endif ?>
	</fieldset>
<?php endforeach ?>
</div>


<div id='add_cate' style="width:450px;display:none" class="plat_tan">
<form id='add_cate_form' >
	<div class="plat_tan_tit"><span></span>添加二级类别</div>
	<div class="plat_tan_page">
		<div class="plat_list">
			<div class="plat_list_left">商品类型：</div>
			<div class="plat_list_right">
				<select style="width:280px;" class="select_1" name="fid">
				<?php foreach ($topCate as $key => $value): ?>
					<option value="<?php echo $key ?>"><?php echo $value ?></option>
				<?php endforeach ?>
				</select>
			</div>
			<div class="clear"></div>
		</div>
		<div class="plat_list">
			<div class="plat_list_left">二级类别：</div>
			<div class="plat_list_right"><input type="text" style="width:280px; color:#999;" value="" name="name" class="input_1"></div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="plat_tan_footer"><span class="cance2_button">取消</span><span class="save_button1">确定</span></div>
</form>
</div>

<script type="text/javascript">

$('#add_act').click(function() {
	popDialog($('#add_cate'));
})

$('.save_button1').click(function() {
	$('#add_cate_form').form_ajax_submit('<?php echo $this->url("addCate") ?>');
})

</script>
