<?php 

		$c=\Ivy::app()->user->getState('company_info');
		var_dump($pager);
?>


<div class="page_title"><div class="page_time"><span class="plat_tianjia">添加商品</span></div>商品管理</div>
<div class="page_add">
    <span class="plat_shai">筛选</span>
    <span class="page_add_span"><img width="20" height="20" src="<?php echo $this->basePath('public');?>/images/plat_add.png"></span>
    <span class="page_add_text">首页 &gt; 商品管理</span>
</div>
    
<div style="text-align:left;" class="page">
	<div class="shopping_text"><span class="batch_button">批量上传</span><a class="blue" href="#">下载商品信息模板</a><font class="hui_666">
	（我们强烈建议您在建立期初数据时，使用<span class="blue">批量上传</span>功能。请先下载商品信息模板。）</font></div>
	<div class="start_page_main">
        <table width="100%" cellspacing="0" cellpadding="0" border="0" class="start_table">
          <tbody><tr>
            <th width="150" style="border-left:none;">商品名称</th>
            <th width="100">商品编码</th>
            <th>商品分类</th>
            <th>单价</th>
            <th>单位</th>
            <th>规格</th>
            <th>用量</th>
            <th width="120">操作</th>
          </tr>
          <tr>
            <td style="border:none;" colspan="8"><div class="start_nothing">无商品信息,请 <span class="start_nothing_span" id='add_act'>添加商品</span></div></td>
          </tr>
          <tr>
            <td>唇膏1号</td>
            <td>&nbsp;</td>
            <td>家居产品</td>
            <td>500</td>
            <td>支</td>
            <td>3.8g</td>
            <td>&nbsp;</td>
            <td><span class="hui_666"><a class="hui_666" href="#">修改</a> | <a class="hui_666" href="#">删除</a></span></td>
          </tr>
          <tr>
            <td>唇膏1号</td>
            <td>&nbsp;</td>
            <td>家居产品</td>
            <td>500</td>
            <td>支</td>
            <td>3.8g</td>
            <td>&nbsp;</td>
            <td><span class="hui_666"><a class="hui_666" href="#">修改</a> | <a class="hui_666" href="#">删除</a></span></td>
          </tr>
          <tr>
            <td>唇膏1号</td>
            <td>&nbsp;</td>
            <td>院装产品</td>
            <td>500</td>
            <td>支</td>
            <td>3.8g</td>
            <td>&nbsp;</td>
            <td><span class="hui_666"><a class="hui_666" href="#">修改</a> | <a class="hui_666" href="#">删除</a></span></td>
          </tr>
          <tr>
            <td>唇膏1号</td>
            <td>&nbsp;</td>
            <td>通用产品</td>
            <td>500</td>
            <td>支</td>
            <td>3.8g</td>
            <td>&nbsp;</td>
            <td><span class="hui_666"><a class="hui_666" href="#">修改</a> | <a class="hui_666" href="#">删除</a></span></td>
          </tr>
          <tr>
            <td>唇膏1号</td>
            <td>&nbsp;</td>
            <td>家居产品</td>
            <td>500</td>
            <td>支</td>
            <td>3.8g</td>
            <td>&nbsp;</td>
            <td><span class="hui_666"><a class="hui_666" href="#">修改</a> | <a class="hui_666" href="#">删除</a></span></td>
          </tr>
          <tr>
            <td colspan="8">分页</td>
          </tr>
        </tbody></table>
	</div>
</div>


<div id='add_prod' style="width:450px;display:none" class="plat_tan">
  <div class="plat_tan_tit"><span></span>添加商品</div>
    <div class="plat_tan_page">
      <div class="plat_list">
          <div class="plat_list_left">商品名称：</div>
            <div class="plat_list_right"><input type="text" style="width:280px; color:#999;" value="请输入门店名称" class="input_1"></div>
            <div class="clear"></div>
        </div>
        <div class="plat_list">
          <div class="plat_list_left">商品编码：</div>
            <div class="plat_list_right"><input type="text" style="width:280px; color:#999;" value="填写该门店拥有实操房间数量" class="input_1"></div>
            <div class="clear"></div>
        </div>
        <div class="plat_list">
          <div class="plat_list_left">商品分类：</div>
            <div class="plat_list_right">
            <select style="width:280px;" class="select_1" name="">
              <option>-----请选择-----</option>
              <option>院装</option>
              <option>家装</option>
              <option>通用</option>
            </select>
          </div>
            <div class="clear"></div>
        </div>
        <div class="plat_list">
          <div class="plat_list_left">单价：</div>
            <div class="plat_list_right"><input type="text" style="width:280px; color:#999;" value="" class="input_1"></div>
            <div class="clear"></div>
        </div>
        <div class="plat_list">
          <div class="plat_list_left">规格：</div>
            <div class="plat_list_right"><input type="text" style="width:280px; color:#999;" value="" class="input_1"></div>
            <div class="clear"></div>
        </div>
        <div class="plat_list">
          <div class="plat_list_left">用量：</div>
            <div class="plat_list_right"><input type="text" style="width:280px; color:#999;" value="" class="input_1"></div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="plat_tan_footer"><span class="cance2_button">取消</span><span class="save_button1">确定</span></div>
</div>

<script type="text/javascript">

$('#add_act').click(function() {
    popDialog($('#add_prod'));
})


</script>