<!--顶部-->
<div class="plat_top">
    <div class="plat_top_logo"><a href="#"><img src="<?php echo $this->basePath('public'); ?>/images/logo.png" width="290" height="30" /></a></div>
    <div class="plat_top_user">
        <a href="<?php echo $this->url('index/logout');?>">
        	<div class="plat_top_user_img"><img src="<?php echo $this->basePath('public'); ?>/images/photo.jpg" width="36" height="36" /><span></span></div>
            <div class="plat_top_user_name"><p class="plat_font_14">理员</p><p class="plat_font_12 plat_color">经理</p></div>
        </a>
        <i></i>
    </div>
    <div class="plat_notice">
    	<ul>
            <li><div class="plat_notice_1"><img src="<?php echo $this->basePath('public'); ?>/images/baojing_1.png" width="25" height="25" /><span>2</span></div></li>
            <li><div class="plat_notice_1"><img src="<?php echo $this->basePath('public'); ?>/images/email_1.png" width="25" height="25" /><span>3</span></div></li>
        </ul>
    </div>
</div>

<!--左侧导航-->
<?php echo Ivy::app()->widget('top/nav'); ?>
<?php //echo Ivy::app()->hook('widget/nav/index'); ?>
<!--左侧导航js-->
<script type="text/javascript" src="<?php echo $this->basePath('public');?>/js/nav.js"></script>

        