<?php
$themePath = $this->basePath('public');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>好哇连锁管控平台</title>
<link href="<?php echo $this->basePath('public'); ?>/css/style.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="<?php echo $this->basePath('public/js/jquery.js'); ?>"></script>
</head>
<body>
<!--顶部-->
<div class="plat_top">
  <div class="plat_top_logo"><a href="javascript:;"><img src="<?php echo $themePath; ?>/images/logo.png" width="290" height="30" /></a></div>
  <div class="plat_top_user">
  	<div class="plat_top_user_img"><img src="<?php echo $themePath; ?>/images/photo.jpg" width="36" height="36" /><span></span></div>
    <div class="plat_top_user_name"><p class="plat_font_14">管理员</p><p class="plat_font_12 plat_color">经理</p></div>
    <i></i>
    <div class="plat_user_main" style="width:140px;">
    	<div class="plat_user_main_ico"></div>
        <ul>
        	<li><a href="#">我的资料</a></li>
            <li><a href="#">修改密码</a></li>
            <li><a href="#">退出登录</a></li>
        </ul>
    </div>
  </div>
</div>

<div class="start_menu">
</div>

<!--内容-->
<div class="start_page">
	<div class="start_page_content">
   	  <div class="start_page_add">注册公司列表</div>
   	  <div class="start_page_main">
   	    <table width="100%" border="0" cellspacing="0" cellpadding="0" class="start_table">
   	      <tr>
   	        <th width="150" style="border-left:none;">公司名称</th>
   	        <th>公司地址</th>
   	        <th>门店数量</th>
   	        <th>联系人</th>
   	        <th>职务</th>
   	        <th>联系电话</th>
   	        <th>Email</th>
   	        <th width="120">操作</th>
          </tr>
          <?php if(empty($model)): ?>
   	      <tr>
   	        <td colspan="8" style="border:none;"><div class="start_nothing">无注册公司信息</div></td>
          </tr>
          <?php else: ?>
          <?php foreach($model as $key => $val): ?>
   	      <tr style="border:0;">
   	        <td><?php echo $val['company_name']; ?></td>
   	        <td><?php echo $val['pca_province'],$val['pca_city'],' ',$val['address']; ?></td>
   	        <td><?php echo $val['store_num']; ?></td>
   	        <td><?php echo $val['contact_name']; ?></td>
   	        <td><?php echo $val['position']; ?></td>
   	        <td><?php echo $val['phone']; ?></td>
   	        <td><a href="mailto:<?php echo $val['email']; ?>"><?php echo $val['email']; ?></a></td>
   	        <td>
	   	        <span class="hui_666">
	   	        	<a href="javascript:;" company_id="<?php echo $val['id']; ?>" class="hui_666 audit_btn">审核通过</a>
	   	        </span>
   	        </td>
          </tr>
          <?php endforeach; ?>
          <?php endif; ?>
        </table>
   	  </div>
   	  <div class="start_page_main"></div>
	</div>
</div>
<script type="text/javascript">
//审核通过
$('.audit_btn').click(function() {
	var _self = $(this);
	var ajax_url = "<?php echo $this->controller->url('audit'); ?>";
	var company_id = _self.attr('company_id');
	$.ajax({
		url : ajax_url,
		data : { 'company_id' : company_id },
		type : 'get',
		dataType : 'json',
		success : function(json) {
			if(json.statusCode == '200') {
				alert(json.message);
				history.go(0);
			}
			else {
				alert(json.message);
			}
		},
		error : function(XMLHttpRequest, textStatus, errorThrown) {
			alert(textStatus);
		}
	});
});
</script>
</body>
</html>
