<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache, must-revalidate">
    <meta http-equiv="expires" content="0">
    <meta name="language" content="en" />
	<title><?php echo $title; ?></title>
	<link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('public/css/style.css'); ?>">
	<script type="text/javascript" src='<?php echo $this->basePath('public/js/jquery.js'); ?>'></script>
	<script type="text/javascript" src='<?php echo $this->basePath('public/js/jquery.pjax.js'); ?>'></script>
</head>