<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<?php  Ivy::app()->widget('index/header'); ?>
<body>


<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12">
			<div class="navbar" style="margin-top: 40px;">
				<div class="navbar-inner">
					<div class="container-fluid">
						 <a data-target=".navbar-responsive-collapse" data-toggle="collapse" class="btn btn-navbar"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></a> <a href="#" class="brand">网站名</a>
						<div class="nav-collapse collapse navbar-responsive-collapse">
							<ul class="nav">
								<li class="active">
									<a href="#">主页</a>
								</li>
								<li>
									<a href="#">链接</a>
								</li>
								<li>
									<a href="#">链接</a>
								</li>
								<li class="dropdown">
									 <a data-toggle="dropdown" class="dropdown-toggle" href="#">下拉菜单<strong class="caret"></strong></a>
									<ul class="dropdown-menu">
										<li>
											<a href="#">下拉导航1</a>
										</li>
										<li>
											<a href="#">下拉导航2</a>
										</li>
										<li>
											<a href="#">其他</a>
										</li>
										<li class="divider">
										</li>
										<li class="nav-header">
											标签
										</li>
										<li>
											<a href="#">链接1</a>
										</li>
										<li>
											<a href="#">链接2</a>
										</li>
									</ul>
								</li>
							</ul>
							<ul class="nav pull-right">
								<li>
									<form class="navbar-form navbar-left" role="search">
										<div class="form-group">
											<input class="form-control" type="text" /> <button type="submit" class="btn btn-default">Go!</button>
										</div>
									</form>
								</li>
								<li class="divider-vertical">
								</li>
								<li class="dropdown">
									 <a data-toggle="dropdown" class="dropdown-toggle" href="#">下拉菜单<strong class="caret"></strong></a>
									<ul class="dropdown-menu">
										<li>
											<a href="#">下拉导航1</a>
										</li>
										<li>
											<a href="#">下拉导航2</a>
										</li>
										<li>
											<a href="#">其他</a>
										</li>
										<li class="divider">
										</li>
										<li>
											<a href="#">链接3</a>
										</li>
									</ul>
								</li>
							</ul>
						</div>
						
					</div>
				</div>
				
			</div>
			<div class="carousel slide" id="carousel-481166">
				<ol class="carousel-indicators">
					<li data-slide-to="0" data-target="#carousel-481166">
					</li>
					<li data-slide-to="1" data-target="#carousel-481166">
					</li>
					<li data-slide-to="2" data-target="#carousel-481166">
					</li>
				</ol>
				<div class="carousel-inner">
					<div class="item active left">
						<img alt="" src="http://www.bootcss.com/p/layoutit/img/1.jpg" />
						<div class="carousel-caption">
							<h4>
								棒球
							</h4>
							<p>
								棒球运动是一种以棒打球为主要特点，集体性、对抗性很强的球类运动项目，在美国、日本尤为盛行。
							</p>
						</div>
					</div>
					<div class="item next left">
						<img alt="" src="http://www.bootcss.com/p/layoutit/img/2.jpg" />
						<div class="carousel-caption">
							<h4>
								冲浪
							</h4>
							<p>
								冲浪是以海浪为动力，利用自身的高超技巧和平衡能力，搏击海浪的一项运动。运动员站立在冲浪板上，或利用腹板、跪板、充气的橡皮垫、划艇、皮艇等驾驭海浪的一项水上运动。
							</p>
						</div>
					</div>
					<div class="item">
						<img alt="" src="http://www.bootcss.com/p/layoutit/img/3.jpg" />
						<div class="carousel-caption">
							<h4>
								自行车
							</h4>
							<p>
								以自行车为工具比赛骑行速度的体育运动。1896年第一届奥林匹克运动会上被列为正式比赛项目。环法赛为最著名的世界自行车锦标赛。
							</p>
						</div>
					</div>
				</div> <a data-slide="prev" href="#carousel-481166" class="left carousel-control">‹</a> <a data-slide="next" href="#carousel-481166" class="right carousel-control">›</a>
			</div>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span8">
			<ul class="thumbnails">
				<li class="span4">
					<div class="thumbnail">
						<img alt="300x200" src="http://www.bootcss.com/p/layoutit/img/people.jpg" />
						<div class="caption">
							<h3>
								冯诺尔曼结构
							</h3>
							<p>
								也称普林斯顿结构，是一种将程序指令存储器和数据存储器合并在一起的存储器结构。程序指令存储地址和数据存储地址指向同一个存储器的不同物理位置。
							</p>
							<p>
								<a class="btn btn-primary" href="#">浏览</a> <a class="btn" href="#">分享</a>
							</p>
						</div>
					</div>
				</li>
				<li class="span4">
					<div class="thumbnail">
						<img alt="300x200" src="http://www.bootcss.com/p/layoutit/img/city.jpg" />
						<div class="caption">
							<h3>
								哈佛结构
							</h3>
							<p>
								哈佛结构是一种将程序指令存储和数据存储分开的存储器结构，它的主要特点是将程序和数据存储在不同的存储空间中，进行独立编址。
							</p>
							<p>
								<a class="btn btn-primary" href="#">浏览</a> <a class="btn" href="#">分享</a>
							</p>
						</div>
					</div>
				</li>
				<li class="span4">
					<div class="thumbnail">
						<img alt="300x200" src="http://www.bootcss.com/p/layoutit/img/sports.jpg" />
						<div class="caption">
							<h3>
								改进型哈佛结构
							</h3>
							<p>
								改进型的哈佛结构具有一条独立的地址总线和一条独立的数据总线，两条总线由程序存储器和数据存储器分时复用，使结构更紧凑。
							</p>
							<p>
								<a class="btn btn-primary" href="#">浏览</a> <a class="btn" href="#">分享</a>
							</p>
						</div>
					</div>
				</li>
			</ul>
            
            
            <div>
                <div id="loading"><img src="<?php echo $this->basePath('public/img/loading.gif'); ?>" /></div>
                <div id="container_main"></div>
            
                <!-- 弹出框 -->
                <a id="modal-702644" href="#modal-container-702644" role="button" class="btn" data-toggle="modal">触发遮罩窗体</a>
    			<div id="modal-container-702644" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    				<div class="modal-header">
    					 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    					<h3 id="myModalLabel">
    						标题栏
    					</h3>
    				</div>
    				<div class="modal-body">
    					<p>
    						显示信息
    					</p>
    				</div>
    				<div class="modal-footer">
    					 <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button> <button class="btn btn-primary">保存设置</button>
    				</div>
    			</div>
            </div>
			
            
		</div>
		<div class="span4">
        <?php if(!empty($article['data'])):?>
            <ol>
            <?php foreach ($article['data'] as $v):?>
                <li><a href="<?php echo $this->url("index/view",array("id"=>$v['id'],"name"=>"大")) ?>"><?php echo $v['title']?><span>(<?php echo $v['author']?>)</span></a></li>
            <?php endforeach;?>
            </ol>
            <!-- 翻页器 -->
            
            <div class="pagination pagination-small pagination-centered" id='pagener'>
				<ul>
					<li>
						<a href="javascript:;" data-num='<?php echo $article['currentpage'] - 1 > 0 ? $article['currentpage']-1 : 1?>'>上一页</a>
					</li>
                    <?php foreach ($article['pagener'] as $val):?>
                		<?php if($val == $article['currentpage']):?>
                			<li><a href="javascript:;" data-num='<?php echo $val?>' class='page_active'><?php echo $val?></a></li>
                		<?php else:?>
                			<li><a href="javascript:;" data-num='<?php echo $val?>'><?php echo $val?></a></li>
                		<?php endif?>
                	<?php endforeach;?>
                    
					<li>
						<a href="#">1</a>
					</li>
					<li>
						<a href="#">2</a>
					</li>
					<li>
						<a href="javascript:;" data-num='<?php echo $article['currentpage'] + 1 <= $article['pageNums'] ? $article['currentpage']+1 : $article['pageNums']?>'>下一页</a>
					</li>
				</ul>
			</div>
            
           
        
        <?php else:?>
        	<div id='message_info'>暂无相关文章！</div>
		<?php endif?>
        
        
			
		</div>
	</div>
</div>







<div id='footer'>
    <?php Ivy::app()->widget('admin/index/index',array('id'=>1,'name'=>"小明")); ?>
</div>


</body>
</html>
<script type="text/javascript">

$("#pagener a").click(function(){
    location.href='<?php echo $this->url("index") ;?>&p='+$(this).attr('data-num');
})

$(document).ready(function(){  
    $('#loading').hide(); //隐藏loading  
});
$(document).pjax('a', '#container_main',{scrollTo:false}); //内容替换的容器  
$(document).on('pjax:send', function() {  
    $('#loading').show(); //显示loading  
});  
$(document).on('pjax:complete', function() {  
    $('#loading').fadeOut(1000); //隐藏loading效果  
});
</script> 