<?php
$themePath = $this->basePath ( 'public' );
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>好哇连锁管控平台-注册</title>
<link href="<?php echo $this->basePath('public'); ?>/css/login.css" rel="stylesheet" type="text/css" />
</head>
<body>
	<div class="top">
		<div class="top_center">
			<span
				style="float: right; background-color: #fff; border: solid 1px #ddd; display: inline-block; line-height: 25px; height: 25px; padding-left: 15px; padding-right: 15px; color: #666; font-size: 12px; margin-top: 25px; cursor: pointer;">返回首页</span>
			<div class="logo">
				<img src="<?php echo $themePath; ?>/images/howa_logo.png" width="170" height="42" />
			</div>
			<span class="logo_span">注册</span>
		</div>
	</div>
	<div class="page">
		<div class="page_tit buzhou_2">
			<ul>
				<li class="buzhou_1_li">1、填写并提交资料</li>
				<li class="buzhou_1_li">2、审核并等待发送验证码</li>
				<li class="buzhou_1_visit">3、填写账号密码，注册成功</li>
			</ul>
		</div>
		<div class="main">
			<div class="zc_ok_tit">
				<span></span>资料提交成功
			</div>
			<div class="zc_ok_page">我们将在3个工作日内审核并答复，请注意查看您的注册邮箱，我们将尽快给您发送激活链接，谢谢。</div>
		</div>
	</div>
	<div class="footer">
		<div class="footer_center">© Copyright 2011-2014 武汉好哇商业技术有限公司
			鄂ICP备14003221号</div>
	</div>
</body>
</html>