<?php 
namespace init;
?>
<script type="text/javascript"
	src='<?php echo $this->basePath('public/js/jquery.form.js'); ?>'></script>
<div class="start_page">
	<div class="start_page_content">
		<div class="start_page_add">第七步：商品管理</div>
		<div class="shopping_text"><span id="upload_btn" class="batch_button">批量上传</span><a href="javascript:;" class="blue download_btn">下载商品信息模板</a><font class="hui_666">（我们强烈建议您在建立期初数据时，使用<span class="blue">批量上传</span>功能。请先下载商品信息模板。）</font></div>
		<div class="start_page_main">
			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="start_table">
				<tbody>
					<tr>
						<th width="150" style="border-left:none;">商品名称</th>
						<th width="100">商品编码</th>
						<th>商品分类</th>
						<th>单价</th>
						<th>单位</th>
						<th>规格</th>
						<th>用量</th>
						<th width="120">操作</th>
					</tr>
					<?php if(empty($model)):?>
					<tr>
						<td colspan="8" style="border:none;"><div class="start_nothing">无商品信息,请 <span class="start_nothing_span">添加商品</span></div></td>
					</tr>
					<?php else:?>
						<?php foreach ($model as $key => $value):?>
						<tr>
							<td><?php echo $value['product_name'];?></td>
							<td><?php echo $value['product_code'];?></td>
							<td><?php echo \CommonConfig::getProductLevel($value['product_level']);?></td>
							<td><?php echo $value['price'];?></td>
							<td><?php echo \CommonConfig::getProductUnit($value['unit']);?></td>
							<td><?php echo $value['page_size'];?></td>
							<td><?php echo $value['number'];?></td>
							<td><span class="hui_666"><a href="javascript:;"model_id="<?php echo $value['id'];?>" class="hui_666 edit_model">修改</a> | <a href="javascript:;" model_id="<?php echo $value['id'];?>" class="hui_666 del_model">删除</a></span></td>
						</tr>
						<?php endforeach;?>
					<?php endif;?>
					<tr>
						<td colspan="8"><span class="start_nothing_span">继续添加+</span></td>
					</tr>
				</tbody>
			</table>
		</div>
		<div class="start_goto">
			<a href="javascript:;" class="back_up">重置</a>
			<a href="<?php echo $this->url('init/step8');?>" class="xiayibu_a">下一步</a>
		</div>
	</div>
</div>
<div id="update_form" class="plat_tan" style="width: 450px; display: none;">
</div>

<div id="upload_form" class="plat_tan" style="width:450px;display:none;">
	<form action="<?php echo $this->controller->url('upload'); ?>" method="post" enctype="multipart/form-data">
	<div class="plat_tan_tit"><span></span>批量上传商品</div>
    <div class="plat_tan_page">
    	<div class="plat_list">
			<div class="plat_list_left">上传文件：</div>
			<div class="plat_list_right">
				<input type="file" name="file" />
			</div>
			<div class="error_msg" style="color:red; font-size: 14px;"></div>
			<div class="clear"></div>
		</div>
    </div>
    <div class="plat_tan_footer">
	    <span class="cance2_button">取消</span>
	    <span class="save_button1">确定</span>
    </div>
    </form>
</div>
<script type="text/javascript">

//添加,修改
$('.start_nothing_span,.edit_model').click(function() {
	var model_id=$(this).attr('model_id');
	$.ajax({
		url: '<?php echo $this->url("update");?>',
		//async:false,
		data: {id: model_id},
	})
	.done(function(data) {
		$('#update_form').html(data);
		popDialog($('#update_form'));
		console.log("success");
	})
	.fail(function() {
		console.log("error");
	})
	
	
});
//删除
$('.del_model').click(function(event) {
	var model_id=$(this).attr('model_id');
	if(confirm('确定要删除指定数据吗?')){
		$.ajax({
			url: '<?php echo $this->url("delete");?>',
			type: 'POST',
			data: {id: model_id},
		})
		.done(function(data) {
			json=eval("(" + data + ")");
			$('body').append('<div class="back_ok" >'+json.message+'</div>');
            
            setTimeout(function(){
 				$('.back_ok').remove();
 				window.location.reload();
 				clearInterval();
 			},1000) 
			console.log(json);
		})
		.fail(function() {
			console.log("error");
		})
	}
});
//重置
$('.back_up').click(function(event) {
	if(confirm('确定要重置数据吗?')){
		$.ajax({
			url: '<?php echo $this->url("deleteAll");?>',
			type: 'POST',
		})
		.done(function(data) {
			json=eval("(" + data + ")");
			$('body').append('<div class="back_ok" >'+json.message+'</div>');
			setTimeout(function(){
				$('.back_ok').remove();
				window.location.reload();
				clearInterval();
			},3000)
			console.log(json);
		})
		.fail(function() {
			console.log("error");
		})
	}
});
$('#upload_btn').click(function() {
	popDialog($('#upload_form'));
});
$('#upload_form .save_button1').click(function() {
	var _self = $(this);
	var form = $(this).parents('form');
	var url = form.attr('action');
	_self.siblings('.cance2_button').trigger('click');
	var _html = "<div id='loading' style='position:fixed;left:0;width:100%;height:100%;top:0;background:rgb(0, 0, 0);opacity:0.5;filter:alpha(opacity=50);'><div style='position:absolute;  cursor1:wait;left:50%;top:50%;width:auto;height:16px;padding:13px 22px 28px 30px;background: url(<?php echo $this->basePath('public');?>/images/loading.gif) no-repeat scroll 5px 10px;text-indent: -99999px;color:#000;'>正在加载，请等待...</div></div>";
    $('body').append(_html);
	form.ajaxSubmit({
		url : url,
		type : 'post',
		data : {},
		dataType : 'json',
		complete : function() {
			$('#loading').remove();
		},
		success : function(json) {
			if(json.statusCode == '200') {
				form.find('.error_msg').html('');
				var data = json.data;
				var total_num = data.total;
				var success_num = data.success;
				var error_seq = '';
				if(total_num > success_num) {
					error_seq = data.error.join(',');
				}
				var alert_msg = '商品总数：'+total_num+'\n'
								+'成功导入：'+success_num+'\n';
				if(!isEmpty(error_seq)) {
					alert_msg += '出错的序列号：'+error_seq;
				}
				alert(alert_msg);
				history.go(0);
			}
			else {
				var error_msg = json.data;
				form.find('.error_msg').html(error_msg);
			}
		},
		error : function(XMLHttpRequest, textStatus, errorThrown) {
			alert(textStatus);
		}
	});
});
$('.download_btn').click(function() {
	$.ajax({
		url : '<?php echo $this->controller->url('index', array('method' => 'getDownloadFile')); ?>',
		success : function(url) {
			window.location.href = url;
		}
	});
});
</script>