<link href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>"
	rel="stylesheet">
<script type="text/javascript"
	src='<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>'></script>
<div class="start_page">
	<div class="start_page_content">
		<div class="start_page_add">第三步：房间管理</div>
		<div style="height:24px; font-size:12px; color:#f00;"><span style="width:16px; height:16px; display:block; background-image:url(<?php echo $this->controller->themePath; ?>/images/jing.png); float:left; margin-right:5px;"></span>为了在邀约中更好的安排客人，需要对房间内的每张床进行编号。如您的店之前没有给床编号，建议直接用1号、2号这样的编号方法。如以前对床位也取过名字，可以沿用以前的叫法</div>
		<div style="height:1px; line-height:1px; font-size:1px; border-bottom:solid 1px #eee;"></div>
		<form action="<?php echo $this->controller->getRequestUri(); ?>" method="post">
		<?php if(empty($model)): ?>
		<div class="room">没有设置门店</div>
		<?php else: ?>
		<?php foreach($model as $key => $val): ?>
		<div class="room" store_id="<?php echo $val['id']; ?>"><span><?php echo $val['name']; ?></span>-房间设置</div>
		<div class="start_page_main">
			<table width="100%" border="0" cellspacing="0" cellpadding="0" class="start_table">
				<tbody>
					<tr>
						<th width="300" style="border-left:none;">房间名称</th>
						<th>房间床位</th>
						<th width="120">操作</th>
					</tr>
					<?php for($i = 0; $i < $val['room_num']; $i++): ?>
					<tr>
						<td <?php if($i == 0) echo 'style="border:none"'; ?>>
							<input datatype="*" name="room_name[<?php echo $val['id']; ?>][]" type="text" class="input_1 input_room" number="<?php echo $i+1; ?>" value="房间<?php echo $i+1; ?>" style="width:220px;">
						</td>
						<td <?php if($i == 0) echo 'style="border:none"'; ?>>
							<select name="bed[<?php echo $val['id']; ?>][]" class="select_1 select_bed">
								<option value="">请选择该房间的床位数量</option>
								<?php for($j = 1; $j <= 10; $j++): ?>
								<option value="<?php echo $j; ?>"><?php echo $j; ?></option>
								<?php endfor; ?>
							</select>
							<input datatype="*" type="hidden" name="bed_name[<?php echo $val['id']; ?>][]" number="<?php echo $i+1; ?>" value="" />
						</td>
						<td <?php if($i == 0) echo 'style="border:none"'; ?>>
							<span class="hui_666 del_btn"><a href="javascript:;" class="hui_666">删除</a></span>
						</td>
					</tr>
					<?php endfor; ?>
					<tr>
						<td colspan="3"><span class="start_nothing_span add_btn">继续添加+</span></td>
					</tr>
				</tbody>
			</table>
		</div>
		<?php endforeach; ?>
		<?php endif; ?>
		<div class="start_goto">
			<a id="reset_btn" href="javascript:;" class="back_up">重置</a>
			<a id="next_save_btn" class="xiayibu_a" href="javascript:;">下一步</a>
		</div>
		</form>
	</div>
</div>
<div class="plat_tan" style="width:450px;display:none;">
	<div class="plat_tan_tit"><span></span>添加床位</div>
    <div class="plat_tan_page">
    </div>
    <div class="plat_tan_footer">
	    <span class="cance2_button">取消</span>
	    <span class="save_button1">确定</span>
    </div>
</div>
<script type="text/javascript">
//选择床的数量
$(document).on('change', 'select[name^="bed"]', function() {
	var _self = $(this);
	var val = _self.val();
	if(!isEmpty(val) && val > 0) {
		var select_bed = $('.plat_tan');
		var store_id = _self.parents('.start_page_main').prev('.room').attr('store_id');
		var number = _self.siblings('input[name^=bed_name]').attr('number');
		select_bed.attr('store_id', store_id);
		select_bed.attr('number', number);
		var bed_html = '';
		for(var i = 0; i < val; i++) {
			bed_html += '<div class="plat_list">'
				+'<div class="plat_list_left">'+(i+1)+'床名称：</div>'
				+'<div class="plat_list_right"><input type="text" class="input_1" value="床'+(i+1)+'" style="width:280px; color:#999;"></div>'
				+'<div class="clear"></div>'
				+'</div>';
		}
		select_bed.find('.plat_tan_page').html(bed_html);
		popDialog(select_bed);
	}
});
//删除
$(document).on('click', '.del_btn', function() {
	var _self = $(this);
	_self.parent('td').parent('tr').remove();
});
//添加
$(document).on('click', '.add_btn', function() {
	var _self = $(this);
	var last_tr_obj = $('.start_table tr:last-child').prev('tr');
	var store_id = _self.parents('.start_page_main').prev('.room').attr('store_id');
	var bed_name = last_tr_obj.find('select.select_bed').attr('name');
	var room_name = last_tr_obj.find('input.input_room').attr('name');
	var last_number = last_tr_obj.find('input.input_room').attr('number');
	var new_number = parseInt(last_number) + 1;
	
	//选择床位数量的html
	var select_html = '<select name="'+bed_name+'" class="select_1 select_bed"><option value="">请选择该房间的床位数量</option>';
	for(var i = 1; i <= 10; i++) {
		select_html += '<option value="'+i+'">'+i+'</option>';
	}
	select_html += '</select>';
	select_html += '<input datatype="*" type="hidden" name="bed_name['+store_id+'][]" value="" number="'+new_number+'" />';

	//tr行的html
	var tr_html = '<tr><td>'
	+'<input datatype="*" name="'+room_name+'" type="text" class="input_1 input_room" number="'+new_number+'" value="房间'+new_number+'" style="width:220px;">'
	+'</td><td>'
	+select_html
	+'</td><td>'
	+'<span class="hui_666 del_btn"><a href="javascript:;" class="hui_666">删除</a></span>'
	+'</td></tr>';
	last_tr_obj.after(tr_html);
});
//保存床位
$(document).on('click', '.plat_tan .save_button1', function() {
	var _self = $(this);
	var plat_tan_obj = _self.parents('.plat_tan');
	var store_id = plat_tan_obj.attr('store_id');
	var number = plat_tan_obj.attr('number');
	var bed_name_obj = $('input[name="bed_name['+store_id+'][]"][number="'+number+'"]');

	var bed_name_arr = new Array();
	plat_tan_obj.find('.plat_list').each(function(i, e) {
		var bed_name = $(this).find('.plat_list_right input').val();
		bed_name_arr.push(bed_name);
	});
	var bed_name_str = bed_name_arr.join(',');
	bed_name_obj.val(bed_name_str);
	bed_name_obj.siblings('select.select_bed').remove();
	bed_name_obj.before('<span class="bed_name_str">'+bed_name_str+'</span>');
	_self.siblings('span.cance2_button').trigger('click');
});
$('#reset_btn').click(function() {
	history.go(0);
});
$('#next_save_btn').click(function() {
	$('form').submit();
});
//提交之前验证
$('form').Validform({
	tiptype:3,
	ignoreHidden:false
});
</script>
