<script type="text/javascript"
	src='<?php echo $this->basePath('public/js/PCASClass.js'); ?>'></script>
<link href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>"
	rel="stylesheet">
<script type="text/javascript"
	src='<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>'></script>
<form action="<?php echo $this->url('update',array('id'=>(int)$_GET['id']));?>" method="post" id="form" >
<div class="plat_tan_tit">
		<span></span><?php echo empty($model)?'添加':'修改';?>项目
	</div>
	<div class="plat_tan_page">
		<div class="plat_list">
			<div class="plat_list_left">项目名称：</div>
			<div class="plat_list_right">
				<input datatype="*" type="text" class="input_1" value="<?php echo $model->project_name;?>" placeholder="请输入项目名称"
					style="width: 280px;" name="data[project_name]">
			</div>
			<div class="clear"></div>
		</div>
		<div class="plat_list">
			<div class="plat_list_left">项目编码：</div>
			<div class="plat_list_right">
				<input datatype="*" type="text" class="input_1" value="<?php echo $model->project_code;?>" placeholder="请输入项目编码"
					style="width: 280px;" name="data[project_code]">
			</div>
			<div class="clear"></div>
		</div>
		<div class="plat_list">
			<div class="plat_list_left">项目分类：</div>
			<div class="plat_list_right">
				<select name="data[project_level]" datatype="*"  class="select_1">
					<?php
					 $variable=\CommonConfig::getProjectLevel();
					 foreach ($variable as $key => $value):
					?>
					<option value="<?php echo $key;?>"  <?php if($key==$model->project_level):?>selected="selected"<?php endif;?>><?php echo $value;?></option>
					<?php endforeach;?>
				</select>
			</div>
			<div class="clear"></div>
		</div>
		<div class="plat_list">
			<div class="plat_list_left">疗程总价：</div>
			<div class="plat_list_right">
				<input datatype="*" onkeyup="if(isNaN(value))execCommand('undo')" onafterpaste="if(isNaN(value))execCommand('undo')" type="text" class="input_1" value="<?php echo $model->price;?>" placeholder="请输入疗程总价(不带单位,默认元)"
					style="width: 280px;" name="data[price]">
			</div>
			<div class="clear"></div>
		</div>
		<div class="plat_list">
			<div class="plat_list_left">疗程数：</div>
			<div class="plat_list_right">
				<input datatype="*" onkeyup="this.value=this.value.replace(/\D/g,'')" onafterpaste="this.value=this.value.replace(/\D/g,'')"  type="text" class="input_1" value="<?php echo $model->num?$model->num:1;?>" placeholder="请输入疗程数"
					style="width: 280px;" name="data[num]">
			</div>
			<div class="clear"></div>
		</div>
		<div class="plat_list">
			<div class="plat_list_left">手工实耗价：</div>
			<div class="plat_list_right">
				<input datatype="*" onkeyup="if(isNaN(value))execCommand('undo')" onafterpaste="if(isNaN(value))execCommand('undo')" type="text" class="input_1" value="<?php echo $model->practice_price;?>" placeholder="请输入手工实耗价(不带单位,默认元)"
					style="width: 280px;" name="data[practice_price]">
			</div>
			<div class="clear"></div>
		</div>
		<div class="plat_list">
			<div class="plat_list_left">赠送实耗价：</div>
			<div class="plat_list_right">
				<input datatype="*" onkeyup="if(isNaN(value))execCommand('undo')" onafterpaste="if(isNaN(value))execCommand('undo')" type="text" class="input_1" value="<?php echo $model->zs_practice_price;?>" placeholder="请输入赠送实耗价(不带单位,默认元)"
					style="width: 280px;" name="data[zs_practice_price]">
			</div>
			<div class="clear"></div>
		</div>

		<div class="plat_list">
			<div class="plat_list_left">供应商：</div>
			<div class="plat_list_right">
				<select name="data[supplier_id]"  class="select_1">
					<option>--请选择供应商--</option>
					<?php
					 $variable=\admin\CompanySupplier::model()->findAll("company_id={$this->controller->company_id} and status=1");
					 foreach ($variable as $key => $value):
					?>
					<option value="<?php echo $value['id'];?>"  <?php if($value['id']==$model->supplier_id):?>selected="selected"<?php endif;?>><?php echo $value['name'];?></option>
					<?php endforeach;?>
				</select>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="plat_tan_footer">
		<span class="cance2_button">取消</span><span class="save_button1 up_save">确定</span>
	</div>
</form>
<script type="text/javascript">
var is_submit=true;
$('.up_save').click(function(event) {	
	$('#form').submit();
});
//提交验证
$('#form').Validform({
tiptype:3,ignoreHidden:true,
beforeSubmit:function(curform){
		//在验证成功后，表单提交前执行的函数，curform参数是当前表单对象。
		//这里明确return false的话表单将不会提交;
		if(is_submit){
			$('.save_button1').html('正在提交...');
			$.ajax({
					url: $('#form').attr('action'),
					type: 'POST',
					data: $('#form').serialize(),
				})
				.done(function(data) {
					json=eval("(" + data + ")");
					$('body').append('<div class="back_ok" style="z-index:10001">'+json.message+'</div>');
					setTimeout(function(){
						$('.back_ok').remove();
						window.location.reload();
						clearInterval();
					},100)
					console.log("success");
				})
				.fail(function() {
					console.log("error");
				})
			return false;
		}
	}
});
</script>