<script type="text/javascript"
	src='<?php echo $this->basePath('public/js/PCASClass.js'); ?>'></script>
<link href="<?php echo $this->basePath('public/js/Validform/Validform_style.css'); ?>"
	rel="stylesheet">
<script type="text/javascript"
	src='<?php echo $this->basePath('public/js/Validform/Validform_v5.3.2_min.js'); ?>'></script>
<form action="<?php echo $this->url('update',array('id'=>(int)$_GET['id']));?>" method="post" id="form" >
<div class="plat_tan_tit">
		<span></span><?php echo empty($model)?'添加':'修改';?>供应商
	</div>
	<div class="plat_tan_page">
		<div class="plat_list">
			<div class="plat_list_left">供应商名称：</div>
			<div class="plat_list_right">
				<input datatype="*" type="text" class="input_1" value="<?php echo $model->name;?>" placeholder="请输入供应商名称"
					style="width: 280px;" name="data[name]">
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="plat_tan_footer">
		<span class="cance2_button">取消</span><span class="save_button1">确定</span>
	</div>
</form>
<script type="text/javascript">
var is_submit=true;
$('.save_button1').click(function(event) {	
	$('#form').submit();
});
//提交验证
$('#form').Validform({
tiptype:3,ignoreHidden:true,
beforeSubmit:function(curform){
		//在验证成功后，表单提交前执行的函数，curform参数是当前表单对象。
		//这里明确return false的话表单将不会提交;
		if(is_submit){
			$('.save_button1').html('正在提交...');
			$.ajax({
					url: $('#form').attr('action'),
					type: 'POST',
					data: $('#form').serialize(),
				})
				.done(function(data) {
					json=eval("(" + data + ")");
					$('body').append('<div class="back_ok" style="z-index:10001">'+json.message+'</div>');
					setTimeout(function(){
						$('.back_ok').remove();
						window.location.reload();
						clearInterval();
					},100)
					console.log("success");
				})
				.fail(function() {
					console.log("error");
				})
			return false;
		}
	}
});
</script>